
/*
Probar las foreign key en la tabla INGREDIENTE_PLATO, donde ID_PLATO es la primary key de la tabla PLATO y 
NOM_INGR la primary key de INGREDIENTES
*/

INSERT INTO CATEGORIA VALUES ('FUERTE');

INSERT INTO ZONA (NOMBRE, CAPACIDAD, ABIERTO, APTODISCAPACIDAD, DESCRIPCIONTECNICA)
VALUES ('ZONA COLOMBIA', 250, 1, 1, 'Zona tematica de Colombia, comida y ambiente tipicos');

INSERT INTO RESTAURANTES (NOMBRE,REPRESENTANTE,TIPOCOMIDA,ZONA, VALOR_COSTOS,VALOR_VENTAS)
VALUES ('LA BANDEJA PAISA', 'JORGE', 'COMIDA COLOMBIANA', 'ZONA COLOMBIA', 3000,8000);

INSERT INTO INGREDIENTES VALUES ('Papa', 'papa fresca', 'fresh potato');

INSERT INTO PLATO (NOMBRE, DESCRIPCION, TRADUCCION, TIEMPOPREPARACION, COSTOPRODUCCION, PRECIOVENTA, RESTAURANTE, ID_PLATO,
VENDIDOS, DISPONIBLES, TIPO, CATEGORIA)
VALUES ('FILET MIGNON', 'DELICIOSO FILET SERVIDO CON ARROZ Y ENSALADA', 'DELIIOUS MEAT SERVED WITH RICE AND SALAD',
2, 400,2000, 'LA BANDEJA PAISA', 1, 10, 30, 'CARNE', 'FUERTE');

/*
Caso en que las foreign key existan
*/
INSERT INTO INGREDIENTES_PLATO VALUES (1,'Papa');

/*
Caso en que la foreign key ID_PLATO no exista
*/
INSERT INTO INGREDIENTES_PLATO VALUES (2,'Papa');

/*
Caso en que la foreign key NOM_INGR no exista
*/
INSERT INTO INGREDIENTES_PLATO VALUES (1,'Otro');

/*
Para borrar, primero se boora INGREDIENTE_PLATO luego INGREDIENTE, luego PLATO, luego RESTAURANTES, luego ZONA, luego CATEGORIA
*/
DELETE FROM INGREDIENTES_PLATO;
DELETE FROM INGREDIENTES WHERE NOMBRE = 'Papa';
DELETE FROM PLATO WHERE ID_PLATO = 1;
DELETE FROM RESTAURANTES WHERE NOMBRE = 'LA BANDEJA PAISA';
DELETE FROM ZONA WHERE NOMBRE = 'ZONA COLOMBIA';
DELETE FROM CATEGORIA;


