
/*
Probar las foreign key en la tabla PEDIDO_PLATO, donde ID_PLATO es la primary key de la tabla PLATO y 
NUM_PEDIDO la primary key de PEDIDO
*/


INSERT INTO USUARIOS VALUES ('jc.ruiz@sa.com', 'Juan Camilo', 100000);

INSERT INTO PEDIDO VALUES (1, 100, '23/05/2016', 'jc.ruiz@sa.com', 1, 0, '12:03:10 AM');

INSERT INTO CATEGORIA VALUES ('FUERTE');

INSERT INTO ZONA (NOMBRE, CAPACIDAD, ABIERTO, APTODISCAPACIDAD, DESCRIPCIONTECNICA)
VALUES ('ZONA COLOMBIA', 250, 1, 1, 'Zona tematica de Colombia, comida y ambiente tipicos');

INSERT INTO RESTAURANTES (NOMBRE,REPRESENTANTE,TIPOCOMIDA,ZONA, VALOR_COSTOS,VALOR_VENTAS)
VALUES ('LA BANDEJA PAISA', 'JORGE', 'COMIDA COLOMBIANA', 'ZONA COLOMBIA', 3000,8000);

INSERT INTO PLATO (NOMBRE, DESCRIPCION, TRADUCCION, TIEMPOPREPARACION, COSTOPRODUCCION, PRECIOVENTA, RESTAURANTE, ID_PLATO,
VENDIDOS, DISPONIBLES, TIPO, CATEGORIA)
VALUES ('FILET MIGNON', 'DELICIOSO FILET SERVIDO CON ARROZ Y ENSALADA', 'DELIIOUS MEAT SERVED WITH RICE AND SALAD',
2, 400,2000, 'LA BANDEJA PAISA', 1, 10, 30, 'CARNE', 'FUERTE');

/*
Caso en que las foreign key existan
*/
INSERT INTO PEDIDO_PLATO VALUES (1,1);

/*
Caso en que la foreign key ID_PLATO no exista
*/
INSERT INTO PEDIDO_PLATO VALUES (2,1);

/*
Caso en que la foreign key NUM_PEDIDO no exista
*/
INSERT INTO PEDIDO_PLATO VALUES (1,2);

/*
Para borrar, primero se boora PEDIDO_PLATO luego PLATO, luego RESTAURANTES, luego ZONA, luego CATEGORIA, luego PEDIDO, luego USUARIO
*/
DELETE FROM PEDIDO_PLATO;
DELETE FROM PLATO WHERE ID_PLATO = 1;
DELETE FROM RESTAURANTES WHERE NOMBRE = 'LA BANDEJA PAISA';
DELETE FROM ZONA WHERE NOMBRE = 'ZONA COLOMBIA';
DELETE FROM CATEGORIA;
DELETE FROM PEDIDO;
DELETE FROM USUARIOS;


