
/*
Probar las foreign key en la tabla PLATO, donde RESTAURANTE es la primary key de la tabla RESTAURANTES y CATEGORIA es la primary 
key de la tabla CATEGORIA
*/

INSERT INTO ZONA (NOMBRE, CAPACIDAD, ABIERTO, APTODISCAPACIDAD, DESCRIPCIONTECNICA)
VALUES ('ZONA COLOMBIA', 250, 1, 1, 'Zona tematica de Colombia, comida y ambiente tipicos');

INSERT INTO RESTAURANTES (NOMBRE,REPRESENTANTE,TIPOCOMIDA,ZONA, VALOR_COSTOS,VALOR_VENTAS)
VALUES ('LA BANDEJA PAISA', 'JORGE', 'COMIDA COLOMBIANA', 'ZONA COLOMBIA', 3000,8000);

INSERT INTO CATEGORIA VALUES('FUERTE');

/*
Caso en que ambas foreign key existen
*/
INSERT INTO PLATO (NOMBRE, DESCRIPCION, TRADUCCION, TIEMPOPREPARACION, COSTOPRODUCCION, PRECIOVENTA, RESTAURANTE, ID_PLATO,
VENDIDOS, DISPONIBLES, TIPO, CATEGORIA)
VALUES ('FILET MIGNON', 'DELICIOSO FILET SERVIDO CON ARROZ Y ENSALADA', 'DELIIOUS MEAT SERVED WITH RICE AND SALAD',
2, 400,2000, 'LA BANDEJA PAISA', 2, 10, 30, 'CARNE', 'FUERTE');

/*
Caso en que la foreign key de RESTAURANTES no existe
*/
INSERT INTO PLATO (NOMBRE, DESCRIPCION, TRADUCCION, TIEMPOPREPARACION, COSTOPRODUCCION, PRECIOVENTA, RESTAURANTE, ID_PLATO,
VENDIDOS, DISPONIBLES, TIPO, CATEGORIA)
VALUES ('FILET ', 'DELICIOSO FILET SERVIDO CON ARROZ Y ENSALADA', 'DELIIOUS MEAT SERVED WITH RICE AND SALAD',
2, 400,2000, 'El toro', 3, 10, 30, 'CARNE', 'FUERTE');


/*
Caso en que la foreign key de CATEGORIA no existe
*/
INSERT INTO PLATO (NOMBRE, DESCRIPCION, TRADUCCION, TIEMPOPREPARACION, COSTOPRODUCCION, PRECIOVENTA, RESTAURANTE, ID_PLATO,
VENDIDOS, DISPONIBLES, TIPO, CATEGORIA)
VALUES ('FILET', 'DELICIOSO FILET SERVIDO CON ARROZ Y ENSALADA', 'DELIIOUS MEAT SERVED WITH RICE AND SALAD',
2, 400,2000, 'LA BANDEJA PAISA', 4, 10, 30, 'CARNE', 'OTRO');


/*
Se debe borrar primero el PLATO, luego la CATEGORIA y el RESTAURANTE y finalemnte la ZONA
*/
DELETE FROM PLATO WHERE ID_PLATO = 2;
DELETE FROM CATEGORIA WHERE NOMCATEGORIA = 'FUERTE';
DELETE FROM RESTAURANTES WHERE NOMBRE = 'LA BANDEJA PAISA';
DELETE FROM ZONA WHERE NOMBRE = 'ZONA COLOMBIA';






