insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pepper - Roasted Red', 'Champagne', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pepper - Roasted Red', 'Soap Cleaner', 'Harb');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pepper - Roasted Red', 'Compound - Orange', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pepper - Roasted Red', 'Nut Pecan', 'Golf Course');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pepper - Roasted Red', 'Hagen Daz', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Coffee Swiss', 'Hagen Daz', 'Golf Course');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Coffee Swiss', 'Soap Cleaner', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Coffee Swiss', 'Flour Rye', 'Stang');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Coffee Swiss', 'Honey Comb', 'Emmet');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Coffee Swiss', 'Fruit Punch', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pork - Ham', 'Soap Cleaner', 'Harb');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pork - Ham', 'Flour Rye', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pork - Ham', 'Bar Special K', 'Stang');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pork - Ham', 'Sobe - Berry Energy', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Apple', 'Soap Cleaner', 'Golf Course');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Apple', 'Flour Rye', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Apple', 'Bar Special K', 'Harb');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Apple', 'Sobe - Berry Energy', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Duck ', 'Apron', 'Sherman');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Duck ', 'Tray ', 'Harbort');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Duck ', 'Sobe - Berry Energy', 'Sherman');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Duck ', 'Pastrami', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Shrimp - Black', 'Apron', 'Harbort');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Shrimp - Black', 'Tray ', 'Harb');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Shrimp - Black', 'Liver', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Shrimp - Black', 'Sage ', 'Crowley');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pork Sausage g', 'Liver', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pork Sausage g', 'Sage ', 'Crowley');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pork Sausage g', 'Cheese Blue', 'Harb');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Pork Sausage g', 'Soy Protein', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Relish', 'Cheese Blue', 'Knutson');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Relish', 'Soy Protein', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Relish', 'Veal - Loin', 'Waubesa');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Relish', 'Sugar - Brown', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Water Cherry', 'Veal - Loine', 'Harbort');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Water Cherry', 'Sugar - Brown', 'Dayton');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Water Cherry', 'Pork Pig', 'Eastlawn');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Water Cherry', 'Pork Prager', 'Wayridge');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Water Cherry', 'Sobe Fuel', 'Ramsey');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Chicken Breast', 'Pork Pig', 'Harb');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Chicken Breast', 'Pork Prager', 'Harbort');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Chicken Breast', 'Sobe Fuel', 'Di Loreto');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Chicken Breast', 'Salmon ', 'Di Loreto');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Butternut', 'Salmon ', 'Nelson');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Butternut', 'Dibs', 'Starling');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Butternut', 'Red Bell', 'Eagan');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Butternut', 'Black Tower', 'Heath');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Cheese Ri', 'Dibs', 'Manley');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Cheese Ri', 'Red Bell', 'Continental');
insert into EQUIVALENTES (ingrediente1, ingrediente2, restaurante_nombre) values ('Cheese Ri', 'Black Tower', 'Stang');
