insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Pepper - Roasted Red', 'nullam varius nulla facilisi cras n maecenas', 'augue aliquam erat volutpasto');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Coffee Swiss', 'enim blandit mi in porttitor pede', 'integer ac neque duis brutrum');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Pork - Ham', 'ridiculus mus vivamuspenatibunt montes', 'odio cras mi  vulputate jblandit ultrices');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Apple', 'blandit laciniamodo placerat praesent blandit nam nulr', 'nam  lobortis ligula sit amet eleilestie');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Duck ', 'rhonct ager aliquet massr', 'metus vitae ipm sit amet di');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Shrimp - Black', 'vitae quam suspenitor lacus at turpis mauris morbi', 'luc vel nisl duis ac');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Pork Sausage g', 'faucibus accumsan odio cunisi volutpat bi vel', 'isque ultrices phasellus id sapien in sapien');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Relish', 'nam dui proin leo oduat ut nulla sed', 'neque aenean auid nisl venenatis lacinia aendio cras');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Water Cherry', 'eleifend usto sit amet sapiee ipsum primis in', 'magnadit nam nulla integet tincidunt eget tempus');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Chicken Breast', 'pretium niam erat volutpat usto in', 'libero h quisque id justo sit amet sapien');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Butternut', 'eget congue egeellus in felisbero nam', 'coellentesque viverra pede ac');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Cheese Ri', 'maecenas pulvit nulla tempus vivamus in', 'nisl duis lis sed intansto eu massa donec');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Champagne', 'praesen blandit non interdum in antum ante', 'in in faucibus orci lia curae duis');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Soap Cleaner', 'justo aliquam isque mauris sit', 'aliquam quis turpisaccumsan tortor quis turpis');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Nut Pecan', 'eros viverraellus in felis mper sapien a libero', 'odio  nisi volutpat eleifend donec ut dolor');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Hagen Daz', 'ante vestus et', 'rhoncus sed vestibulum sit amet cssa id lobortis');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Flour Rye', 'nunc nisl duis bibendumtitor pede justo a donec dapibus', 'aenmassa id nisl venenusto morbi ut odio');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Honey Comb', 'nibh in hac habitasse icitudin vitae', 'phasellus sit amet ersus mi nulla ac');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Fruit Punch', 'faretra magna vestibulum aliquet ultrices', 'rhoncus rpis integer');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Bar Special K', 'donec vitae nisi nam nulla pede ullamcorper augue a sused', 'arcu libero rutrumnam');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Sobe - Berry Energy', 'integer a m lacus morcenas leo odio', 'mala integer pede justo lacinia egetmpus vel pede morbi');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Valdobiaddene', 'nibh in hac ect eget rutrum at lorem integer', 'risus la sit amet eleifend pede liam molestie nibh');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Bread - Roll', 'posuere aliquet ultrices erat tortor sollicitudin mi', 'platea dictumst  nulla ut erat');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Coffee Capsule', 'vitaonec quis orci egeolutpat', 'ellputate nonummy maecenunt');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Pastrami', 'eget ibero nam dui', 'libero quis orciat nulla suspendisse potenti');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Apron', 'quam et rutrum at lorem incidunnia erat vestibulum', 'aliqa bibendum');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Tray ', 'sagittis sapien cum  nascetur ridiculus mus', ' rutrum at lorem integer tincidunt ante vel');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Bran Maple ', '  dignissim vestibulum vestibulum ante', ' diam nam tristique tortor eu pede');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Eggs Canned', ' dapibus duis at velit eu', 'id nulla luctus');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Liver', ' enim  euismod scelerisque quam turpis', ' venenatis tristique  diam id ornare imperdiet sapien');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Sage ', 'tincidunt eget tempus ornare', ' magna vulputate luctus');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Cheese Blue', 'as tristique est  ac consequat', ' faucibus orci luctus et ultrices');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Soy Protein', 'convallis vestibulum', 'varius integer mattis');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Veal - Loin', ' scelerisque  lorem vitae mattis nibh ligula', ' a eget eros');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Timberlay', 'ac nulla  dapibus nulla', 'dapibus augue quis');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Water 500ml', ' volutpat in congue etiam justo', 'quam primis in faucibus');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Pasta Bauletti', 'ibh in at nulla', 'ut erat id  cras');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Sugar - Brown', ' orci vehicula condimentum', 'quis augue luctu gravida nisi');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Flour - Semolina', ' vestibulum ante ipsum', ' nulla sed vel enim sit');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Ecolab - Lime ', 'nam augue', 'placerat ante nulla quis');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Aspic ', 'nulla ac enim in tempor', 'hac habitasse platea');
insert into INGREDIENTES (nombre, descripcion, traduccion) values (' Steak Cohoe', 'maecenas pulvinar cursus', 'turpis aliquam sit');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Flour as', ' curae', ' nec condimentum neque sapien');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Pork Pig', 'lobortis ecursus vestibulum', 'aenean in imperdiet et commodo');
insert into INGREDIENTES (nombre, descripcion, traduccion) values (' Mix Corn ', ' facilisi cras non velit', ' congue eget semper');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Pork Prager', ' nisi venenatis tristique', 'odio pulvinar lobortis est');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Sobe Fuel', ' dolor morbi vel lectus', ' ac consequat metus sapien ut');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Dc  Fu', ' lectus suspendisse potenti', 'at  volutpat erat');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Sauce Pepper', ' non ligula  id sapien', 'cursus  nec euismod');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Butternut', ' platea dictumst', ' est quam pharetra magna');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Cheese  Wine', ' congue eget', 'commodo vel pede');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Kiwi ', 'interd vivamus metus', 'sed volutpat dui maecenas');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Garlic Peeled', 'nisl aenean lectus pellentes', ' at  odio consequat varius');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Bread Panko', 'id as sas', 'varius non mattis');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Juice  Apple', ' in faucibus orci', 'eu montes nascetur');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Beer - Maudite', ' vestibulum sed', 'in suspendisse potenti');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Ice - Clear', 'risuante', 'nibh  magna  cum');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Olives Dired', ' at dolor quis odio', 'in leo amet erat');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Thai Dreg', ' justo platea', 'amet sapien ultrices posuere');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Bone Out', 'llus nisi eu orci', ' lacus purus aliquet at');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Hungarian', 'nonummy maecenas', 'odio lectus in');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Cabernet ', 'libero integer a', ' sapien turpis');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Radish ', 'donec  faucibus orci luctus', '  in felis donec semper');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Raspberries - Fresh', 'a nibh in quis justo maecenas', 'bibendum lacus morbi sem');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Pork - Liver', ' est phasellus sit', 'orci luctus vitae');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Dill', ' pellentesque ultrices', ' sollicitudin mi');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Nantucket - Carrot Orange', 'metus vitae ipsum aliquam', 'odio donec ut');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Salmon ', 'dui  vel lectus in', 'felis eu ac enim');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Trigger', 'olor morbi vel lectus ', 'ante  posuere  curae');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Dibs', 'et sapien dignissim', 'id   ante nulla');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Sauce - Balsamic Viniagrette', ' dapibus augue vel', 'potenti  non mauris');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Red Bell', ' dapibus duis at velit', 'maecenas  ut erat');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('BGoodhearth', 'in qua sed ', ' ass interdum');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Black Tower', ' primis in', 'metus eget nunc donec');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Energy Drink - Redbull 355ml', ' potenti nullam porttitor lacus', ' dolor quis odio');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Stock -Fish', 'tincidunt ante', 'nibh ligula integer');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Inside ', 'velit vestibulum', ' sed  in tempus sit amet');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Mix Carrot', ' quisque ut', ' velit donec diam neque');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Wine Noir ', 'ame tortor quis', 'sem dui vel sem');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Lettuce ', ' vulputate vitae', 'morbi nunc rhoncus dui');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Skirt ', ' sapien in sapien', 'mi  nulla tellus in ');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Sauce Caesar ', 'urna ut tellus', 'mis  in est');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Bread ', ' nisl aenean lectus', ' purus phasellus in felis');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Veal -', ' pede venenatis', 'suscipit  tellus semper');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Chicken Thigh - Bone Out', ' cubilia curae curabitur', ' orci nullam molestie nibh in');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Lotus Root', 'ante in', ' mauris');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Dried Cherries', 'q phasellus  sapien', ' vel enim');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Juice - Clam, 46 Oz', '  id lobortis', ' sapien a libero nam dui');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Puff Pastry - Sheets', ' nulla sed vel enim sit amet', ' convallis eget eleifend luctus');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('The Pop Shoppe - Lime Rickey', '  volutpat dui', 'mauris non velit nec');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Sage - Fresh', ' posuere cubilia curae', 'ut tellus nulla ut  nulla facilisi');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Wine - Red, Black Opal Shiraz', ' eu sapien cursus vestibulum proin', 'augue vel accumsan tellus nisi eu ');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Soup - Campbells Chicken', 'mauris morbi', 'potenti magnis ridiculus');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Pepsi - Diet, 355 Ml', ' sociis natoque penatibus et', 'enim  dapibus');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Food Colouring - Orange', ' sit amet', ' quisque  libero rutrum ac lobortis vel');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Muffins - Assorted', ' praesent lectus', ' amet consectetuer adipiscing');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Rum - White, Gg White', ' id luctus nec molestie sed', ' sagittis sapien');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Chips - Assorted', ' maecenas rhoncus', ' eu interdum eu tincidunt in leo');
insert into INGREDIENTES (nombre, descripcion, traduccion) values ('Cheese - St. Andre', 'cidunt  amet erat', 'consequat metus sapien');
