insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Away We Go', 1526, 8556, 2, 20, 1, 38, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Stuck in Love', 1591, 7982, 82, 13, 2, 21, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Pulp Fiction', 2518, 6323, 3, 11, 3, 34, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('The Last of the Finest', 2076, 4330, 83, 2, 4, 36, 'Harbort');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Night at the Museum: Battle of the Smithsonian', 1631, 4735, 67, 0, 5, 29, 'Crowley');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Fair Game', 1109, 9938, 48, 14, 6, 35, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Wild Zero', 2785, 6563, 56, 7, 7, 27, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Mouse Hunt', 1323, 4970, 40, 0, 8, 32, 'Sherman');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('The Perfect World of Kai', 2306, 7195, 68, 19, 9, 32, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Hard Day''s Night, A', 2886, 3331, 52, 16, 10, 37, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('North', 2050, 9777, 97, 7, 11, 28, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Willow', 2579, 7415, 3, 18, 12, 35, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Lost Skeleton of Cadavra, The', 1536, 7361, 3, 11, 13, 38, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Ordet (Word, The)', 1266, 4179, 81, 18, 14, 33, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Claustrofobia', 1062, 8590, 3, 9, 15, 22, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Deeper Shade of Blue, A', 2474, 6208, 1, 5, 16, 27, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Best Foot Forward', 1749, 3084, 86, 19, 17, 22, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Holocaust', 1212, 7059, 65, 15, 18, 29, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Fahrenheit 451', 2438, 3545, 77, 11, 19, 38, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Godfather: Part III, The', 1908, 3435, 55, 1, 20, 32, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Tuulikaappimaa', 2820, 3442, 99, 1, 21, 20, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Die Another Day', 2647, 6526, 5, 15, 22, 40, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Secret Six, The', 2467, 8208, 74, 16, 23, 25, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Father Hood', 1854, 9617, 7, 9, 24, 32, 'Golf Course');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Our Vinyl Weighs a Ton: This Is Stones Throw Records', 1007, 6542, 24, 10, 25, 20, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Working Girl', 2830, 3273, 89, 9, 26, 34, 'Golf Course');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Scanners', 1308, 4230, 80, 14, 27, 32, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Lookout, The', 2736, 5004, 60, 14, 28, 26, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Good Morning, Babylon', 1306, 3241, 29, 6, 29, 32, 'Harbort');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('See You Tomorrow, Everyone', 2772, 5172, 85, 5, 30, 37, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Music Never Stopped, The', 2685, 6656, 95, 8, 31, 20, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Charlie Chan in Panama', 2582, 3041, 73, 17, 32, 30, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('River, The', 1377, 6980, 34, 5, 33, 20, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Quickie, The', 2698, 6473, 25, 16, 34, 25, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Promised Life, The (Vie promise, La)', 2488, 9954, 1, 20, 35, 26, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Ten Little Indians', 1775, 9232, 8, 5, 36, 24, 'Stang');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Snowbeast', 2006, 8816, 96, 0, 37, 23, 'Golf Course');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Big Knife, The', 2953, 7983, 6, 13, 38, 34, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Subject Was Roses, The', 2049, 8174, 68, 12, 39, 36, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Double Life of Veronique, The (Double Vie de Véronique, La)', 2027, 8096, 80, 10, 40, 25, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Dick Tracy vs. Cueball', 1332, 6114, 37, 2, 41, 26, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Sign ''o'' the Times', 1084, 4722, 86, 0, 42, 25, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('In the Park', 2333, 9262, 64, 18, 43, 32, 'Harbort');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Ballad of the Paper Balloons (a.k.a. Humanity and Paper Balloons) (Ninjô kami fûsen)', 1364, 8278, 3, 0, 44, 40, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Tooth Fairy', 1566, 7364, 62, 4, 45, 38, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Virginia City', 1413, 9148, 5, 15, 46, 23, 'Stang');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('In Order of Disappearance (Kraftidioten)', 2330, 5622, 67, 12, 47, 26, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Greatest Movie Ever Sold, The (POM Wonderful Presents: The Greatest Movie Ever Sold)', 2214, 6101, 23, 18, 48, 24, 'Harbort');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Diên Biên Phú', 1779, 4457, 19, 15, 49, 27, 'Harbort');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Fate Is the Hunter', 2123, 4778, 10, 13, 50, 30, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Raw Deal', 1236, 9050, 96, 6, 51, 22, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Adaptation', 2944, 8428, 80, 13, 52, 30, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Green Fire', 2355, 4715, 46, 12, 53, 23, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('As Far As My Feet Will Carry Me (So weit die Füße tragen)', 1062, 9317, 43, 0, 54, 21, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Man Hunt', 1550, 4587, 77, 9, 55, 23, 'Harbort');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Dead Girl, The', 2247, 3678, 20, 7, 56, 27, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Claudine', 1624, 6711, 87, 10, 57, 27, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('World Apart, A', 1108, 6788, 85, 18, 58, 35, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Conscientious Objector, The', 1327, 6971, 69, 9, 59, 24, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Take Out', 2363, 3670, 20, 18, 60, 28, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Beijing Bicycle (Shiqi sui de dan che)', 1319, 8771, 69, 8, 61, 20, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Shadow of the Vampire', 2688, 7341, 35, 19, 62, 24, 'Harbort');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('6 Days to Air: The Making of South Park', 2865, 9909, 47, 7, 63, 35, 'Stang');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Trap, The (Klopka)', 1937, 7461, 79, 17, 64, 20, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Winter Passing', 1213, 7214, 93, 4, 65, 22, 'Ramsey');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Year One, The (L''an 01)', 2094, 6603, 39, 2, 66, 40, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Young Philadelphians, The', 2249, 3584, 65, 9, 67, 29, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Pistol Whipped', 2200, 9239, 82, 16, 68, 40, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Live Flesh (Carne trémula)', 2319, 5345, 46, 8, 69, 28, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Needful Things', 2070, 9731, 25, 5, 70, 36, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Rise of the Footsoldier', 1391, 7049, 57, 19, 71, 26, 'Harbort');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Wet Hot American Summer', 2826, 4372, 94, 9, 72, 28, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Cheeky Girls', 1169, 6937, 26, 2, 73, 27, 'Harbort');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('That Day (Ce jour-là)', 2237, 8040, 24, 15, 74, 35, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Kingdom of the Spiders', 2952, 6104, 50, 15, 75, 33, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Jodorowsky Constellation, The (La constellation Jodorowsky)', 2629, 8353, 21, 15, 76, 24, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Decoys 2: Alien Seduction ', 1722, 3644, 30, 11, 77, 35, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Finder''s Fee', 2272, 3903, 58, 5, 78, 31, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Over Your Dead Body', 2172, 9596, 49, 19, 79, 37, 'Golf Course');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Mr. Baseball', 1146, 4700, 32, 15, 80, 25, 'Harbort');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('This Is My Life', 2156, 7785, 3, 4, 81, 40, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('It', 1137, 5590, 54, 2, 82, 40, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Ghost Goes West, The', 2956, 9055, 22, 10, 83, 37, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('My Man Godfrey', 1289, 6992, 21, 15, 84, 29, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Without Love', 2550, 7201, 34, 9, 85, 35, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Dragon Ball Z: Wrath of the Dragon (Doragon bôru Z 13: Ryûken bakuhatsu!! Gokû ga yaraneba dare ga yaru)', 2728, 6593, 26, 14, 86, 29, 'Crowley');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Halo Legends', 2099, 3755, 33, 10, 87, 37, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('When Harry Met Sally...', 1603, 9653, 56, 11, 88, 30, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Jerichow', 1981, 5048, 93, 18, 89, 35, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Proposition, The', 2554, 4955, 20, 12, 90, 22, 'Di Loreto');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Honey, I Blew Up the Kid', 1776, 3474, 71, 18, 91, 31, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Giant Claw, The', 2792, 6065, 15, 4, 92, 25, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('A Magnificent Haunting', 1342, 7476, 77, 19, 93, 20, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Johnny Mnemonic', 2454, 4213, 96, 0, 94, 37, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Felony', 2322, 8183, 79, 17, 95, 20, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Dead Men Don''t Wear Plaid', 2879, 5406, 70, 11, 96, 36, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Song to Remember, A', 2464, 7537, 41, 0, 97, 26, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Barretts of Wimpole Street, The (a.k.a. Forbidden Alliance)', 2512, 6066, 32, 3, 98, 36, 'Dayton');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Brothers (Brødre)', 2579, 6877, 93, 16, 99, 35, 'Harb');
insert into MENU (nombre, costoprod, preciovent, vendidos, disponibles, id_menu, max_disp, nomrestaurante) values ('Mr. Jones', 1893, 9014, 61, 15, 100, 20, 'Harb');
