insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Tremblay, Breitenberg and Lowe', 186, 1, 0, 'amet erat nulla tempus vivamus in');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Roberts LLC', 332, 1, 0, 'hac habitasse platea dictumst etiam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Herzog, Barrows and Nitzsche', 181, 0, 0, 'felis eu sapien cursus vestibulum proin eu mi nulla ac');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Krajcik, Rempel and Abernathy', 656, 0, 0, 'nulla elit ac nulla sed vel enim');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Trantow-Swift', 336, 1, 1, 'eget tincidunt eget tempus vel pede morbi');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('O''Keefe-Gutkowski', 688, 0, 0, 'duis ac nibh fusce lacus purus aliquet at');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Torp, Simonis and Green', 462, 0, 0, 'luctus et ultrices posuere cubilia curae nulla dapibus dolor');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Breitenberg LLC', 307, 1, 0, 'pulvinar lobortis est phasellus sit amet erat nulla');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Hackett, Barrows and Monahan', 994, 1, 0, 'turpis integer aliquet massa id lobortis convallis tortor risus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Von-Stiedemann', 727, 1, 1, 'gravida nisi at nibh in hac habitasse');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Reynolds, Stokes and Collins', 581, 1, 1, 'in hac habitasse platea dictumst maecenas ut massa');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Cole LLC', 658, 0, 0, 'neque duis bibendum morbi non quam nec');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Hyatt Group', 467, 1, 0, 'vitae mattis nibh ligula nec sem duis aliquam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Medhurst, Yost and Ratke', 592, 1, 1, 'condimentum id luctus nec molestie sed justo pellentesque viverra pede');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Yost-Ebert', 409, 0, 1, 'nisi at nibh in hac');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Sauer LLC', 135, 0, 1, 'lorem integer tincidunt ante vel ipsum');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Bauch, Wuckert and Tremblay', 716, 0, 0, 'suspendisse potenti cras in purus eu');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Kutch-Koch', 812, 1, 0, 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Zemlak, Wisoky and Hermiston', 517, 1, 0, 'dapibus dolor vel est donec');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Cronin, Muller and Bechtelar', 930, 1, 1, 'in congue etiam justo etiam pretium iaculis justo in hac');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Zboncak, DuBuque and Koch', 804, 1, 1, 'quam a odio in hac habitasse platea dictumst');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Koelpin, Corwin and Kulas', 512, 0, 1, 'non pretium quis lectus suspendisse potenti in eleifend');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Ward Inc', 309, 0, 1, 'suscipit nulla elit ac nulla sed');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Herzog LLC', 380, 1, 1, 'risus auctor sed tristique in');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Killdeer', 877, 1, 0, 'non lectus aliquam sit amet diam in magna');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Braun and Sons', 414, 1, 0, 'turpis sed ante vivamus tortor duis mattis egestas metus aenean');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Mayert-VonRueden', 897, 1, 0, 'condimentum id luctus nec molestie sed justo pellentesque viverra');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Goodland', 700, 0, 0, 'nunc purus phasellus in felis donec semper');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Adams-Osinski', 516, 0, 0, 'dolor morbi vel lectus in');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Cassin, Sipes and Fritsch', 591, 1, 1, 'vulputate nonummy maecenas tincidunt lacus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Mosciski and Sons', 896, 0, 0, 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Garrison', 871, 0, 1, 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Schiller, Bauch and Adams', 656, 1, 0, 'bibendum imperdiet nullam orci pede');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Hessel LLC', 416, 0, 0, 'sed augue aliquam erat volutpat in congue etiam justo etiam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Huels, Kuhic and Padberg', 604, 0, 0, 'mi sit amet lobortis sapien sapien non');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Maggio, Bernhard and Skiles', 956, 0, 1, 'risus auctor sed tristique in tempus sit');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Corwin Group', 766, 1, 0, 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Mandrake', 353, 1, 1, 'venenatis lacinia aenean sit amet justo morbi ut odio cras');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Schowalter Inc', 880, 0, 1, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Armstrong LLC', 347, 0, 1, 'nulla elit ac nulla sed vel');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Littel-Vandervort', 140, 1, 0, 'aliquet ultrices erat tortor sollicitudin mi sit amet');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Senger Inc', 638, 1, 0, 'viverra pede ac diam cras pellentesque volutpat dui maecenas');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Kunde-Rice', 181, 1, 0, 'libero nullam sit amet turpis elementum ligula vehicula consequat');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Dibbert, Berge and Ankunding', 486, 0, 1, 'erat tortor sollicitudin mi sit');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Hintz Group', 824, 0, 0, 'vulputate elementum nullam varius nulla facilisi cras');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Schaden LLC', 100, 1, 1, 'at ipsum ac tellus semper interdum mauris ullamcorper purus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Bayer, Davis and MacGyver', 278, 0, 0, 'lorem id ligula suspendisse ornare');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Lueilwitz-Tillman', 439, 0, 1, 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Cassin LLC', 389, 1, 0, 'vestibulum sit amet cursus id turpis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Torp-Hayes', 705, 0, 1, 'nulla elit ac nulla sed vel enim sit amet');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Schaden Group', 520, 0, 1, 'ac tellus semper interdum mauris ullamcorper purus sit');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Frami, Swaniawski and Haley', 847, 1, 0, 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Schultz, Block and Spinka', 283, 1, 0, 'sed interdum venenatis turpis enim blandit mi in');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Jaskolski-Will', 671, 1, 1, 'est phasellus sit amet erat nulla tempus vivamus in felis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Kutch Group', 264, 1, 0, 'adipiscing lorem vitae mattis nibh ligula nec sem duis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Upton-D''Amore', 252, 1, 1, 'curae nulla dapibus dolor vel est');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Fay Inc', 910, 1, 0, 'adipiscing lorem vitae mattis nibh ligula nec sem duis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Thiel, Franecki and Stamm', 566, 1, 0, 'accumsan tortor quis turpis sed ante vivamus tortor duis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Kautzer, Koepp and Lakin', 611, 0, 0, 'integer aliquet massa id lobortis convallis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('McGlynn, Bashirian and Bogan', 562, 0, 1, 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Hessel-Johnston', 638, 0, 1, 'sed accumsan felis ut at dolor quis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('D''Amore-Kutch', 836, 0, 1, 'ligula in lacus curabitur at ipsum');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Bogan, Gerhold and Parker', 883, 0, 0, 'morbi quis tortor id nulla ultrices');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Okuneva-Kub', 913, 0, 0, 'est lacinia nisi venenatis tristique fusce congue diam id');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Weimann and Sons', 509, 0, 0, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('O''Connell, Runolfsdottir and Sanford', 179, 0, 0, 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Huel, Runte and Wiza', 262, 1, 0, 'quis odio consequat varius integer');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('DuBuque LLC', 886, 0, 0, 'dolor sit amet consectetuer adipiscing elit proin interdum mauris non');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Stehr-Botsford', 401, 1, 0, 'id justo sit amet sapien dignissim vestibulum');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Purdy Group', 891, 0, 0, 'libero convallis eget eleifend luctus ultricies eu nibh');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Jaskolski Inc', 229, 0, 1, 'nibh in lectus pellentesque at nulla');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Wiza Group', 926, 0, 1, 'pede justo eu massa donec dapibus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Crona-O''Reilly', 805, 1, 1, 'ipsum primis in faucibus orci luctus et ultrices');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Yost-Stiedemann', 482, 1, 0, 'vivamus in felis eu sapien cursus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Bernier, Hirthe and White', 438, 0, 0, 'aliquam erat volutpat in congue');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Buckridge, Jenkins and Bashirian', 412, 1, 0, 'a odio in hac habitasse platea');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Greenholt, Mraz and Torp', 493, 0, 0, 'in hac habitasse platea dictumst etiam faucibus cursus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Monahan-Kutch', 158, 0, 0, 'turpis donec posuere metus vitae ipsum aliquam non');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Senger-Zulauf', 949, 0, 0, 'et commodo vulputate justo in blandit ultrices enim');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Auer and Sons', 404, 1, 0, 'convallis morbi odio odio elementum');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Schroeder-Christiansen', 253, 0, 0, 'montes nascetur ridiculus mus etiam vel augue');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Mayer, Abbott and Hartmann', 323, 1, 1, 'felis sed lacus morbi sem mauris laoreet ut rhoncus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Hodkiewicz-Corkery', 475, 0, 1, 'eu est congue elementum in hac habitasse');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Auer, Harvey and Gerhold', 616, 0, 1, 'at nulla suspendisse potenti cras in purus eu magna vulputate');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Cummings-Connelly', 639, 1, 0, 'et ultrices posuere cubilia curae mauris');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Goyette, Hirthe and Huel', 359, 0, 1, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Nicolas-Schroeder', 928, 0, 0, 'vestibulum ante ipsum primis in faucibus orci luctus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Blanda-Ferry', 277, 1, 0, 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Lang LLC', 941, 0, 1, 'quisque id justo sit amet sapien');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Gutkowski, Balistreri and Runte', 197, 0, 0, 'magna bibendum imperdiet nullam orci pede venenatis non sodales');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Halvorson, Miller and Russel', 380, 1, 0, 'cursus vestibulum proin eu mi');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Price, Mayert and VonRueden', 452, 0, 0, 'sem mauris laoreet ut rhoncus aliquet pulvinar sed');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Gulgowski Group', 781, 0, 0, 'ligula suspendisse ornare consequat lectus in');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Lockman, Sporer and Wintheiser', 465, 1, 0, 'commodo vulputate justo in blandit ultrices enim lorem ipsum');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Stracke, Smitham and Conroy', 776, 1, 0, 'tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Cole-Prohaska', 945, 0, 0, 'ultrices posuere cubilia curae mauris viverra diam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Kuhn-Fadel', 809, 0, 0, 'sed vestibulum sit amet cursus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Murazik Group', 765, 1, 0, 'habitasse platea dictumst aliquam augue quam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Halvorson Group', 780, 0, 1, 'ac leo pellentesque ultrices mattis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Harvey and Sons', 748, 1, 1, 'justo nec condimentum neque sapien placerat ante');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Howell Inc', 549, 1, 0, 'quam sapien varius ut blandit non');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Vandervort, Reilly and McCullough', 973, 1, 1, 'potenti cras in purus eu magna vulputate luctus cum sociis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Renner Inc', 563, 1, 0, 'ligula pellentesque ultrices phasellus id sapien in');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Green-Osinski', 139, 0, 0, 'nunc vestibulum ante ipsum primis in faucibus orci');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Kertzmann-Pouros', 638, 0, 0, 'dictumst aliquam augue quam sollicitudin vitae');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Emard-Rosenbaum', 739, 0, 1, 'eu est congue elementum in hac habitasse platea dictumst morbi');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Doyle, Rowe and McDermott', 658, 1, 0, 'fusce posuere felis sed lacus morbi sem mauris laoreet');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Macejkovic LLC', 742, 0, 0, 'in tempus sit amet sem fusce consequat nulla nisl');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Altenwerth-Swift', 646, 0, 0, 'lectus pellentesque at nulla suspendisse potenti cras');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Nolan Inc', 295, 1, 0, 'nunc donec quis orci eget orci vehicula condimentum curabitur in');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Bergstrom and Sons', 233, 1, 1, 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('McClure and Sons', 495, 0, 0, 'commodo placerat praesent blandit nam nulla integer pede justo lacinia');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Jerde-Erdman', 392, 1, 1, 'duis mattis egestas metus aenean fermentum donec ut mauris eget');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Nitzsche-Anderson', 310, 1, 0, 'morbi non quam nec dui luctus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Frami-Nienow', 785, 0, 0, 'id lobortis convallis tortor risus dapibus augue');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Kub-Wolf', 784, 1, 0, 'lacinia erat vestibulum sed magna at nunc commodo placerat');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Kuphal-Lowe', 556, 1, 1, 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('McDermott-Lakin', 889, 0, 0, 'sapien a libero nam dui proin leo odio porttitor id');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Ryan Group', 654, 1, 1, 'volutpat dui maecenas tristique est et tempus semper est quam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Boehm, Mraz and Champlin', 532, 0, 1, 'felis ut at dolor quis odio');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Jenkins-Kilback', 892, 0, 0, 'lorem ipsum dolor sit amet consectetuer');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Deckow-Keebler', 812, 0, 1, 'quam pede lobortis ligula sit amet eleifend pede libero');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Parisian-Howell', 832, 0, 0, 'ut suscipit a feugiat et');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Gutmann-Torp', 628, 1, 1, 'suspendisse ornare consequat lectus in est risus auctor sed');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Purdy Inc', 484, 1, 0, 'penatibus et magnis dis parturient montes');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Stanton LLC', 629, 0, 0, 'cubilia curae nulla dapibus dolor vel est donec');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Gorczany-Blanda', 256, 1, 0, 'odio elementum eu interdum eu tincidunt in leo');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Fay, Kunze and Koss', 359, 0, 1, 'phasellus sit amet erat nulla');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Turcotte-Herman', 845, 1, 0, 'nunc commodo placerat praesent blandit nam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Nikolaus-Ritchie', 691, 0, 0, 'aliquet massa id lobortis convallis tortor risus dapibus augue vel');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Braun-Connelly', 458, 1, 0, 'sem praesent id massa id nisl venenatis lacinia aenean sit');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Block Group', 172, 1, 1, 'quis libero nullam sit amet turpis elementum');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Emard-Bailey', 939, 0, 0, 'lacinia eget tincidunt eget tempus vel pede morbi');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Waters-Kling', 810, 1, 1, 'euismod scelerisque quam turpis adipiscing');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Dickinson Inc', 305, 1, 1, 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Terry Inc', 657, 1, 0, 'lectus pellentesque eget nunc donec quis orci eget');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Schamberger-Stamm', 743, 1, 1, 'non pretium quis lectus suspendisse potenti in eleifend quam a');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Pfannerstill-Monahan', 537, 0, 1, 'odio condimentum id luctus nec molestie sed justo pellentesque viverra');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Windler-Klein', 797, 0, 0, 'in faucibus orci luctus et ultrices posuere');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Yost and Sons', 751, 0, 0, 'dui vel nisl duis ac nibh');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Murray-Stracke', 655, 0, 1, 'nec sem duis aliquam convallis nunc proin at turpis a');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Okuneva-Ortiz', 110, 0, 1, 'parturient montes nascetur ridiculus mus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Ledner-Ebert', 833, 0, 0, 'curabitur in libero ut massa');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Friesen-Robel', 647, 1, 1, 'morbi a ipsum integer a nibh in');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Dwight', 546, 1, 1, 'sed ante vivamus tortor duis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Abshire LLC', 369, 0, 1, 'justo sollicitudin ut suscipit a');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Cole LLC', 649, 0, 0, 'lectus vestibulum quam sapien varius ut blandit non');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Rosenbaum and Sons', 811, 1, 0, 'ac est lacinia nisi venenatis tristique fusce congue diam id');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Corkery and Sons', 561, 0, 0, 'sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Lyons', 889, 0, 1, 'iaculis justo in hac habitasse');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Spencer, Volkman and Legros', 280, 1, 1, 'nulla ultrices aliquet maecenas leo odio');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Keebler LLC', 140, 0, 1, 'massa id lobortis convallis tortor');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Runolfsson and Sons', 856, 1, 1, 'dis parturient montes nascetur ridiculus mus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Flatley LLC', 243, 0, 1, 'tempus sit amet sem fusce');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Hills Inc', 661, 0, 1, 'erat curabitur gravida nisi at nibh in hac habitasse');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Labadie LLC', 991, 1, 0, 'pellentesque ultrices phasellus id sapien in sapien iaculis congue');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Senger-MacGyver', 310, 1, 0, 'phasellus in felis donec semper sapien a libero nam dui');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Towne, Lowe and Pollich', 485, 1, 0, 'ipsum dolor sit amet consectetuer adipiscing elit proin');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Klocko and Sons', 208, 1, 0, 'tortor id nulla ultrices aliquet maecenas leo');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Hyatt, Gutmann and Heidenreich', 895, 0, 0, 'et ultrices posuere cubilia curae duis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Sauer-Wilderman', 699, 0, 1, 'in sagittis dui vel nisl');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Towne, Farrell and Vandervort', 555, 1, 0, 'elementum in hac habitasse platea dictumst morbi vestibulum');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Zemlak Inc', 379, 0, 1, 'blandit nam nulla integer pede justo lacinia');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Hilpert, Greenfelder and Towne', 150, 1, 0, 'maecenas tincidunt lacus at velit vivamus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Dicki, Breitenberg and Streich', 305, 1, 1, 'eu est congue elementum in hac habitasse');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Ullrich, Graham and Ruecker', 461, 0, 1, 'tristique est et tempus semper est quam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Schumm-Kunze', 499, 0, 0, 'elementum ligula vehicula consequat morbi a ipsum integer a');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Zemlak, Kling and Mayert', 741, 1, 1, 'odio in hac habitasse platea dictumst maecenas');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('O''Keefe-Gleichner', 418, 1, 1, 'amet nulla quisque arcu libero rutrum ac');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Maggio, Boyer and Pollich', 387, 0, 1, 'enim leo rhoncus sed vestibulum sit amet cursus id');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Ratke, Lindgren and Jacobson', 962, 1, 0, 'at velit eu est congue elementum');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Toy-Green', 737, 0, 1, 'pede lobortis ligula sit amet eleifend pede');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Kunze LLC', 915, 0, 1, 'in congue etiam justo etiam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Hoppe, Langworth and Murphy', 545, 1, 0, 'non quam nec dui luctus rutrum nulla tellus in');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Nicolas LLC', 384, 1, 1, 'felis sed lacus morbi sem mauris laoreet');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Fahey-Kuhn', 800, 0, 0, 'morbi vel lectus in quam fringilla');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Reynolds Inc', 581, 1, 1, 'turpis integer aliquet massa id lobortis convallis tortor risus dapibus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Mueller, Rosenbaum and Lueilwitz', 644, 0, 0, 'ipsum aliquam non mauris morbi');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Jast-McCullough', 118, 0, 1, 'nisl aenean lectus pellentesque eget nunc donec quis orci');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Borer Inc', 932, 0, 1, 'rutrum neque aenean auctor gravida sem praesent');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Kris, Abbott and Nader', 122, 1, 1, 'et commodo vulputate justo in');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Veum, Larkin and Jacobson', 549, 0, 0, 'leo odio porttitor id consequat in');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Mertz Group', 553, 0, 0, 'nibh in hac habitasse platea dictumst');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Gibson Group', 637, 1, 0, 'condimentum curabitur in libero ut massa');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Bins, Nicolas and Mitchell', 275, 0, 0, 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Carroll, Beahan and Hirthe', 529, 1, 1, 'at vulputate vitae nisl aenean lectus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Kuphal-Funk', 904, 1, 0, 'nulla suscipit ligula in lacus curabitur at ipsum');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Robel-Schimmel', 216, 1, 1, 'nulla ultrices aliquet maecenas leo odio condimentum id luctus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Bahringer-Rolfson', 431, 0, 1, 'erat nulla tempus vivamus in felis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Schuppe Inc', 650, 0, 1, 'nulla sed vel enim sit');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Luettgen-Kuhn', 112, 0, 1, 'vel nisl duis ac nibh fusce lacus purus');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Cruickshank Inc', 375, 1, 1, 'sagittis nam congue risus semper porta volutpat');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Baumbach, Gerlach and Howe', 435, 1, 0, 'porttitor lacus at turpis donec posuere');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Roberts, Hickle and Shanahan', 889, 0, 0, 'commodo vulputate justo in blandit ultrices enim lorem');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Strosin-Olson', 879, 0, 0, 'cubilia curae mauris viverra diam vitae quam');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Grimes-Green', 771, 1, 0, 'hac habitasse platea dictumst maecenas');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Fadel and Sons', 829, 1, 1, 'leo odio porttitor id consequat in consequat ut nulla sed');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('O''Conner-Weimann', 175, 0, 1, 'augue a suscipit nulla elit');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Gerhold, Thompson and Wolf', 424, 0, 1, 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis');
insert into ZONA (nombre, capacidad, abierto, aptodiscapacidad, descripciontecnica) values ('Weber-Reichel', 906, 1, 0, 'tristique est et tempus semper');
