SELECT DISTINCT * FROM (USUARIOS JOIN   ON PEDIDO.EMAIL_USER = USUARIOS.EMAIL)
WHERE PEDIDO.FECHA BETWEEN TO_DATE('10-10-2015', 'DD/MM/YYYY') AND TO_DATE('10-10-2016', 'DD/MM/YYYY');





(SELECT EMAIL, NOMBRE, IDENTIFICACION FROM USUARIOS JOIN (
(SELECT EMAIL_USER AS EMAIL_USER1
FROM PEDIDO JOIN (PEDIDO_PLATO JOIN PLATO ON PEDIDO_PLATO.ID_PLATO = PLATO.ID_PLATO)
ON PEDIDO.NUM_PEDIDO = PEDIDO_PLATO.NUM_PEDIDO WHERE PLATO.RESTAURANTE = 'RESTAURANTE 10'
AND PEDIDO.FECHA BETWEEN TO_DATE('10-10-2010', 'DD/MM/YYYY') AND TO_DATE('10-10-2011', 'DD/MM/YYYY'))
UNION
(SELECT EMAIL_USER AS EMAIL_USER1
FROM PEDIDO JOIN (PEDIDO_MENUS JOIN MENU ON PEDIDO_MENUS.ID_MENU = MENU.ID_MENU)
ON PEDIDO.NUM_PEDIDO = PEDIDO_MENUS.NUM_PEDIDO WHERE MENU.NOMRESTAURANTE = 'RESTAURANTE 10'
AND PEDIDO.FECHA BETWEEN TO_DATE('10-10-2010', 'DD/MM/YYYY') AND TO_DATE('10-10-2011', 'DD/MM/YYYY')))
ON EMAIL = EMAIL_USER1) ORDER BY EMAIL;




((SELECT EMAIL, NOMBRE, IDENTIFICACION FROM USUARIOS LEFT OUTER JOIN (
(SELECT EMAIL_USER AS EMAIL_USER1
FROM PEDIDO JOIN (PEDIDO_PLATO JOIN PLATO ON PEDIDO_PLATO.ID_PLATO = PLATO.ID_PLATO)
ON PEDIDO.NUM_PEDIDO = PEDIDO_PLATO.NUM_PEDIDO WHERE PLATO.RESTAURANTE = 'RESTAURANTE 10'
AND PEDIDO.FECHA BETWEEN TO_DATE('10-10-2010', 'DD/MM/YYYY') AND TO_DATE('10-10-2011', 'DD/MM/YYYY')))
ON EMAIL = EMAIL_USER1 WHERE EMAIL_USER1 IS NULL) UNION (SELECT EMAIL, NOMBRE, IDENTIFICACION FROM USUARIOS JOIN (
(SELECT EMAIL_USER AS EMAIL_USER1
FROM PEDIDO JOIN (PEDIDO_MENUS JOIN MENU ON PEDIDO_MENUS.ID_MENU = MENU.ID_MENU)
ON PEDIDO.NUM_PEDIDO = PEDIDO_MENUS.NUM_PEDIDO WHERE MENU.NOMRESTAURANTE = 'RESTAURANTE 10'
AND PEDIDO.FECHA BETWEEN TO_DATE('10-10-2010', 'DD/MM/YYYY') AND TO_DATE('10-10-2011', 'DD/MM/YYYY')))
ON EMAIL = EMAIL_USER1 WHERE  EMAIL_USER1 IS NULL))
ORDER BY EMAIL;

SELECT TO_CHAR(FECHA, 'YYYY'), COUNT(*) FROM PEDIDO
GROUP BY TO_CHAR(FECHA, 'YYYY')
ORDER BY TO_CHAR(FECHA, 'YYYY') ASC;

SELECT CT AS PEDIDOS_POR_RESTAURANTE, COUNT(*) FROM (
SELECT RESTAURANTE, COUNT(*) AS CT FROM PEDIDO JOIN
(PEDIDO_PLATO JOIN PLATO ON PLATO.ID_PLATO = PEDIDO_PLATO.ID_PLATO) ON PEDIDO.NUM_PEDIDO = PEDIDO_PLATO.NUM_PEDIDO
GROUP BY RESTAURANTE
ORDER BY CT DESC;
)
GROUP BY CT
ORDER BY CT;

SELECT NOMBRE, EMAIL, IDENTIFICACION FROM (PEDIDO NATURAL JOIN PEDIDO_PLATO NATURAL JOIN CLIENTEFR) WHERE EMAIL NOT IN (SELECT EMAIL_USER
FROM (PEDIDO NATURAL JOIN PEDIDO_MENUS));