DELETE FROM EQUIVALENTES;
DELETE FROM ORGANIZADOR;
DELETE FROM ZONAS_CLIENTESFR;
DELETE FROM RESERVA;
DELETE FROM INGREDIENTES_PLATO;
DELETE FROM INGREDIENTES;
DELETE FROM PEDIDO_PLATO;
DELETE FROM PEDIDO_MENUS;
DELETE FROM MENU_PLATO;
DELETE FROM PEDIDO;
DELETE FROM PLATO;
DELETE FROM MENU;
DELETE FROM CLIENTEFR;
DELETE FROM USUARIOS;
DELETE FROM RESTAURANTES;
DELETE FROM ZONA;
DELETE FROM CATEGORIA;

INSERT INTO CATEGORIA VALUES('FUERTE');

INSERT INTO ZONA (NOMBRE, CAPACIDAD, ABIERTO, APTODISCAPACIDAD, DESCRIPCIONTECNICA)
VALUES ('ZONA COLOMBIA', 250, 1, 1, 'Zona tematica de Colombia, comida y ambiente tipicos');

INSERT INTO RESTAURANTES (NOMBRE,REPRESENTANTE,TIPOCOMIDA,ZONA, VALOR_COSTOS,VALOR_VENTAS)
VALUES ('LA BANDEJA PAISA', 'JORGE', 'COMIDA COLOMBIANA', 'ZONA COLOMBIA', 3000,8000);

INSERT INTO PLATO (NOMBRE, DESCRIPCION, TRADUCCION, TIEMPOPREPARACION, COSTOPRODUCCION, PRECIOVENTA, RESTAURANTE, ID_PLATO,
VENDIDOS, DISPONIBLES, TIPO, CATEGORIA)
VALUES ('FILET MIGNON', 'DELICIOSO FILET SERVIDO CON ARROZ Y ENSALADA', 'DELIIOUS MEAT SERVED WITH RICE AND SALAD',
2, 400,2000, 'LA BANDEJA PAISA', 2, 10, 30, 'CARNE', 'FUERTE');


commit;


