
INSERT INTO RESERVA VALUES (TO_DATE('20/12/2017','DD/MM/YYYY'), 200, 'ZONA COLOMBIA', 1, 'jc.ruiz@uniandes.com');
INSERT INTO RESERVA VALUES (TO_DATE('20/12/2017','DD/MM/YYYY'), 5, 'ZONA COLOMBIA', 1, 'jc.ruiz@uniandes.com');

SELECT * FROM RESERVA;
